Changes per feedback from @philpennock

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -85,6 +85,8 @@ _do_curl() {
 _sha256sum() {
 	if command -v sha256sum &>/dev/null; then
 		sha256sum "$@"
+	elif command -v gsha256sum &>/dev/null; then
+		gsha256sum "$@"
 	else
 		shasum -a 256 "$@"
 	fi
@@ -100,10 +102,11 @@ _do_curls() {
 	for url in "${@}"; do
 		if _do_curl "${url}" "${f}"; then
 			if _do_curl "${url}.sha256" "${f}.sha256"; then
-				echo "  ${f}" >>"${f}.sha256"
+				echo "$(cat "${f}.sha256")  ${f}" >"${f}.sha256.tmp"
+				mv "${f}.sha256.tmp" "${f}.sha256"
 				if ! _sha256sum -c "${f}.sha256" &>/dev/null; then
-					: sha256sum failed for "${f}"
-					: continuing to next candidate URL
+					echo "gimme: sha256sum failed for '${f}'" >&2
+					echo 'gimme: continuing to next candidate URL' >&2
 					continue
 				fi
 			fi
