use logfile to track invocations, add `gimme clean`
This gives us the other part of multiple git builds, each isolated, per
issue #147.

Caveat: the use of aliases breaks the log-file's utility.  For now, I'm
handling that by not implementing aliases for git and constraining clean
to be only for git.  We can revisit if desired.

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -20,6 +20,7 @@
 #+        -k --known known - list known go versions and exit
 #+    --force-known-update - when used with --known, ignores the cache and updates
 #+    -r --resolve resolve - resolve a version specifier to a version, show that and exit
+#+           --clean clean - remove cached (git) builds not used recently
 #+  -
 #+  Influential env vars:
 #+  -
@@ -44,6 +45,7 @@
 #+     GIMME_DOWNLOAD_BASE - override base URL dir for download (default '${GIMME_DOWNLOAD_BASE}')
 #+        GIMME_LIST_KNOWN - override base URL for known go versions (default '${GIMME_LIST_KNOWN}')
 #+   GIMME_KNOWN_CACHE_MAX - seconds the cache for --known is valid for (default '${GIMME_KNOWN_CACHE_MAX}')
+#+    GIMME_CLEAN_KEEP_FOR - seconds to look back in invocation log to keep a cached build (default '${GIMME_CLEAN_KEEP_FOR}')
 #+  -
 #
 set -e
@@ -132,6 +134,15 @@ else
 			sed 's/\.00*/./g'
 	}
 fi
+
+# _log_invocation "env-name"
+_log_invocation() {
+	(
+		umask 077
+		touch "${GIMME_INVOCATION_LOG}"
+	)
+	printf '%s %s\n' "$(date +%s)" "$1" >>"${GIMME_INVOCATION_LOG}"
+}
 
 # _do_curls "file" "url" ["url"...]
 _do_curls() {
@@ -469,7 +480,7 @@ _try_existing() {
 	git)
 		local resolved_sha
 		resolved_sha="$(_resolve_git_spec "$GIMME_GO_VERSION")" || return 1
-		local existing_ver="${GIMME_VERSION_PREFIX}/git.${resolved_sha}"
+		local existing_ver="${GIMME_VERSION_PREFIX}/git.${resolved_sha}.${GIMME_OS}.${GIMME_ARCH}"
 		local existing_env="${GIMME_ENV_PREFIX}/git.${resolved_sha}.${GIMME_OS}.${GIMME_ARCH}.env"
 		;;
 	*)
@@ -494,6 +505,7 @@ _try_existing() {
 		fi
 		# Export the same variables whether building new or using existing
 		echo "export GIMME_ENV='${existing_env}';"
+		_log_invocation "${existing_env}"
 		return
 	fi
 
@@ -507,6 +519,7 @@ _try_binary() {
 	local bin_tgz="${GIMME_TMP}/go${version}.${GIMME_OS}.${arch}.tar.gz"
 	local bin_dir="${GIMME_VERSION_PREFIX}/go${version}.${GIMME_OS}.${arch}"
 	local bin_env="${GIMME_ENV_PREFIX}/go${version}.${GIMME_OS}.${arch}.env"
+	local result_env
 
 	[[ "${version}" =~ ${ALLOWED_UPSTREAM_VERSION_RE} ]] || return 1
 
@@ -517,13 +530,16 @@ _try_binary() {
 	_binary "${version}" "${bin_tgz}" "${arch}" || return 1
 	_extract "${bin_tgz}" "${bin_dir}" || return 1
 	_env "${bin_dir}" | tee "${bin_env}" || return 1
-	echo "export GIMME_ENV=\"$(_env_alias "${bin_dir}" "${bin_env}")\""
+	result_env="$(_env_alias "${bin_dir}" "${bin_env}")" || return 1
+	echo "export GIMME_ENV=\"${result_env}\""
+	_log_invocation "${result_env}"
 }
 
 _try_source() {
 	local src_tgz="${GIMME_TMP}/go${GIMME_GO_VERSION}.src.tar.gz"
 	local src_dir="${GIMME_VERSION_PREFIX}/go${GIMME_GO_VERSION}.src"
 	local src_env="${GIMME_ENV_PREFIX}/go${GIMME_GO_VERSION}.src.env"
+	local result_env
 
 	[[ "${GIMME_GO_VERSION}" =~ ${ALLOWED_UPSTREAM_VERSION_RE} ]] || return 1
 
@@ -532,7 +548,9 @@ _try_source() {
 	_compile "${src_dir}" || return 1
 	_try_install_race "${src_dir}" || return 1
 	_env "${src_dir}" | tee "${src_env}" || return 1
-	echo "export GIMME_ENV=\"$(_env_alias "${src_dir}" "${src_env}")\""
+	result_env="$(_env_alias "${src_dir}" "${src_env}")" || return 1
+	echo "export GIMME_ENV=\"${result_env}\""
+	_log_invocation "${result_env}"
 }
 
 # We do _not_ try to use any version caching with _try_existing(), but instead
@@ -548,7 +566,7 @@ _try_git() {
 	local resolved_sha
 
 	resolved_sha="$(_resolve_git_spec "$GIMME_GO_VERSION")" || return 1
-	local git_dir="${GIMME_VERSION_PREFIX}/git.${resolved_sha}"
+	local git_dir="${GIMME_VERSION_PREFIX}/git.${resolved_sha}.${GIMME_OS}.${GIMME_ARCH}"
 	local git_env="${GIMME_ENV_PREFIX}/git.${resolved_sha}.${GIMME_OS}.${GIMME_ARCH}.env"
 
 	if [[ -d "${git_dir}" ]]; then
@@ -563,7 +581,11 @@ _try_git() {
 	_compile "${git_dir}" || return 1
 	_try_install_race "${git_dir}" || return 1
 	_env "${git_dir}" | tee "${git_env}" || return 1
-	echo "export GIMME_ENV=\"$(_env_alias "${git_dir}" "${git_env}")\""
+	# We don't use _env_alias with git
+	# Before changing this, consider impact upon what names are logged,
+	# as we use the log for cleanup.
+	echo "export GIMME_ENV=\"${git_env}\""
+	_log_invocation "${git_env}"
 }
 
 _wipe_version() {
@@ -598,6 +620,11 @@ _list_versions() {
 		fi
 		echo
 	done
+	for d in "${GIMME_VERSION_PREFIX}/git".*."${GIMME_OS}".*; do
+		local cleaned="${d##*/git}"
+		cleaned="${cleaned%%.${GIMME_OS}.*}"
+		echo "${cleaned}"
+	done | sort
 }
 
 _update_remote_known_list_if_needed() {
@@ -787,6 +814,45 @@ _assert_version_given() {
 	${ASSERT_ABORT:-exit} 1
 }
 
+# Currently we just clean git builds; we could clean "everything" but that
+# will require careful thought about how to handle aliases in build logs.
+# That would be easy in Various Other Languages.
+_clean_cached_builds() {
+	local min_time env_file last_used
+	min_time=$(($(date +%s) - GIMME_CLEAN_KEEP_FOR))
+	if [[ -n "${GIMME_DEBUG_OVERRIDE_MINTIME:-}" ]]; then
+		min_time="${GIMME_DEBUG_OVERRIDE_MINTIME:?}"
+	fi
+	# comm(1) is obtuse; here we're using process substitution yielding a filename
+	# <( ... )  which has been in Bash for almost as long as it's been in Zsh.
+	# We want "only those which only appear in the first output", so suppress the
+	# other columns.
+	comm -23 \
+		<(awk -v "min_time=$min_time" '$1 < min_time { print $2 }' "${GIMME_INVOCATION_LOG}" | sort -u) \
+		<(awk -v "min_time=$min_time" '$1 >= min_time { print $2 }' "${GIMME_INVOCATION_LOG}" | sort -u) |
+		while read -r env_file; do
+			case "$env_file" in
+			*/git.*) true ;;
+			**) continue ;; # before changing this, consider how to handle aliases
+			esac
+			test -f "$env_file" || continue
+			last_used="$(awk -v "want=$env_file" '$2 == want { print $1 }' "${GIMME_INVOCATION_LOG}" | tail -n 1)"
+			_clean_one_build "$env_file" "$last_used"
+		done
+}
+
+_clean_one_build() {
+	local envfile="${1:?}" last_used_epoch="${2:?}"
+	local base
+	base="$(basename "$envfile")"
+	eval "$(grep GOROOT= "$envfile")"
+	# oh ugh, BSD vs GNU date conversion, I can't be bothered to translate
+	warn "cleaning $base, last used: ${last_used_epoch}"
+	du -hs "$GOROOT" >&2
+	rm -rf -- "$GOROOT" "$envfile"
+	unset GOROOT
+}
+
 _exclude_from_backups() {
 	# Please avoid anything which requires elevated privileges or is obnoxious
 	# enough to offend the invoker
@@ -817,6 +883,7 @@ _to_goarch() {
 : "${GIMME_ARCH:=$(_to_goarch "$(uname -m)")}"
 : "${GIMME_HOSTARCH:=$(_to_goarch "$(uname -m)")}"
 : "${GIMME_ENV_PREFIX:=${HOME}/.gimme/envs}"
+: "${GIMME_INVOCATION_LOG:=${HOME}/.gimme/invoked.log}"
 : "${GIMME_VERSION_PREFIX:=${HOME}/.gimme/versions}"
 : "${GIMME_TMP:=${TMPDIR:-/tmp}/gimme}"
 : "${GIMME_GO_GIT_REMOTE:=https://github.com/golang/go.git}"
@@ -825,6 +892,7 @@ _to_goarch() {
 : "${GIMME_DOWNLOAD_BASE:=https://storage.googleapis.com/golang}"
 : "${GIMME_LIST_KNOWN:=https://golang.org/dl}"
 : "${GIMME_KNOWN_CACHE_MAX:=10800}"
+: "${GIMME_CLEAN_KEEP_FOR:=1209600}"
 
 # The version prefix must be an absolute path
 case "${GIMME_VERSION_PREFIX}" in
@@ -896,6 +964,10 @@ while [[ $# -gt 0 ]]; do
 	--force-known-update | force-known-update)
 		force_known_update=1
 		;;
+	--clean | clean)
+		_clean_cached_builds
+		exit 0
+		;;
 	-i | install)
 		true # ignore a dummy argument
 		;;
@@ -950,9 +1022,10 @@ unset CC_FOR_TARGET
 
 readonly GIMME_VERSION_PREFIX="$(_realpath "${GIMME_VERSION_PREFIX}")"
 readonly GIMME_ENV_PREFIX="$(_realpath "${GIMME_ENV_PREFIX}")"
+readonly GIMME_INVOCATION_LOG="$(_realpath "${GIMME_INVOCATION_LOG}")"
 readonly GIMME_BARE_REPO="${GIMME_VERSION_PREFIX}/common-go.git"
 
-mkdir -p "${GIMME_VERSION_PREFIX}" "${GIMME_ENV_PREFIX}"
+mkdir -p "${GIMME_VERSION_PREFIX}" "${GIMME_ENV_PREFIX}" "$(dirname "${GIMME_INVOCATION_LOG}")"
 # The envs dir stays small and provides a record of what had been installed
 # whereas the versions dir grows by hundreds of MB per version and is not
 # intended to support local modifications (as that subverts the point of gimme)
