gimme: Add arm64 version warning
arm64 support was added in go1.5.  Print an error messsage and fail
if an older version is requested.

Signed-off-by: lupan2005 <lupan2005@gmail.com>
[Split off from larger patch and cleaned up.]
Signed-off-by: Geoff Levand <geoff@infradead.org>

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -427,7 +427,13 @@ fi
 case "${GIMME_ARCH}" in
 	x86_64) GIMME_ARCH=amd64 ;;
 	x86) GIMME_ARCH=386 ;;
-	arm64) ;;
+	arm64)
+		if [[ "${GIMME_GO_VERSION}" < "1.5" ]]; then
+			echo >&2 "error: ${GIMME_ARCH} is not supported by this go version"
+			echo >&2 "try go1.5 or newer"
+			exit 1
+		fi
+	;;
 	arm*) GIMME_ARCH=arm ;;
 esac
 
