gimme: Try binary bootstrap
If an existing bootstrap compler is not found see if a binary
version is avalable.  The exising code would build from git if
no existing was found.

Signed-off-by: lupan2005 <lupan2005@gmail.com>
[Split off from larger patch and cleaned up.]
Signed-off-by: Geoff Levand <geoff@infradead.org>

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -171,24 +171,28 @@ _extract() {
 
 # _setup_bootstrap
 _setup_bootstrap() {
-	local bootstrap_root=""
-	local bootstrap_candidates=(
-		# we just need _a_ working Go 1.4+ build, really
-		"${GIMME_ENV_PREFIX}/go1.6"*".env"
-		"${GIMME_ENV_PREFIX}/go1.5"*".env"
-		"${GIMME_ENV_PREFIX}/go1.4"*".env"
-	)
-	for candidate in "${bootstrap_candidates[@]}" ; do
-		if [ -s "$candidate" ]; then
-			bootstrap_root="$candidate"
-			break
+	local versions=("1.6" "1.5" "1.4")
+
+	# try existing
+	for v in "${versions[@]}" ; do
+		for candidate in "${GIMME_ENV_PREFIX}/go${v}"*".env" ; do
+			if [ -s "$candidate" ]; then
+				export GOROOT_BOOTSTRAP="$(source "${candidate}" 2>/dev/null && go env GOROOT)"
+				return 0
+			fi
+		done
+	done
+
+	# try binary
+	for v in "${versions[@]}" ; do
+		if [ -n  "$(_try_binary ${v} "${GIMME_HOSTARCH}")" ]; then
+			export GOROOT_BOOTSTRAP="${GIMME_VERSION_PREFIX}/go${v}.${GIMME_OS}.${GIMME_HOSTARCH}"
+			return 0
 		fi
 	done
-	if [ -z "${bootstrap_root}" ] ; then
-		echo >&2 "Unable to setup go bootstrap from existing"
-		return 1
-	fi
-	export GOROOT_BOOTSTRAP="$(source "${bootstrap_root}" 2>/dev/null && go env GOROOT)"
+
+	echo >&2 "Unable to setup go bootstrap from existing or binary";
+	return 1;
 }
 
 # _compile "dir"
