gimme: Move code to _setup_bootstrap
To make way for expanding the bootstrap processing pull that
code out into its own function _setup_bootstrap.  Just moves
the code, no functional change.

Signed-off-by: Geoff Levand <geoff@infradead.org>

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -169,28 +169,33 @@ _extract() {
 	tar -xf "${1}" -C "${2}" --strip-components 1
 }
 
+# _setup_bootstrap
+_setup_bootstrap() {
+	local bootstrap_root=""
+	local bootstrap_candidates=(
+		# we just need _a_ working Go 1.4+ build, really
+		"${GIMME_ENV_PREFIX}/go1.6"*".env"
+		"${GIMME_ENV_PREFIX}/go1.5"*".env"
+		"${GIMME_ENV_PREFIX}/go1.4"*".env"
+	)
+	for candidate in "${bootstrap_candidates[@]}" ; do
+		if [ -s "$candidate" ]; then
+			bootstrap_root="$candidate"
+			break
+		fi
+	done
+	if [ -z "${bootstrap_root}" ] ; then
+		echo >&2 "Unable to setup go bootstrap from existing"
+		return 1
+	fi
+	export GOROOT_BOOTSTRAP="$(source "${bootstrap_root}" 2>/dev/null && go env GOROOT)"
+}
+
 # _compile "dir"
 _compile() {
 	(
-		if grep -q GOROOT_BOOTSTRAP "${1}/src/make.bash" &> /dev/null ; then
-			local bootstrap_root=""
-			local bootstrap_candidates=(
-				# we just need _a_ working Go 1.4+ build, really
-				"${GIMME_ENV_PREFIX}/go1.6"*".env"
-				"${GIMME_ENV_PREFIX}/go1.5"*".env"
-				"${GIMME_ENV_PREFIX}/go1.4"*".env"
-			)
-			for candidate in "${bootstrap_candidates[@]}" ; do
-				if [ -s "$candidate" ]; then
-					bootstrap_root="$candidate"
-					break
-				fi
-			done
-			if [ -z "${bootstrap_root}" ] ; then
-				echo >&2 "Unable to setup go bootstrap from existing"
-				return 1
-			fi
-			export GOROOT_BOOTSTRAP="$(source "${bootstrap_root}" 2>/dev/null && go env GOROOT)"
+		if grep -q GOROOT_BOOTSTRAP "${1}/src/make.bash" &> /dev/null; then
+			_setup_bootstrap || return 1
 		fi
 		cd "${1}"
 		if [[ -d .git ]] ; then
